server:
  port: ${SERVER_PORT}

swagger:
  uri: ${SWAGGER_URI}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: "${REDIS_PASSWORD}"

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: "${DB_PASSWORD}"
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL}

  batch:
    job:
      enabled: ${BATCH_JOB_ENABLED}
    jdbc:
      initialize-schema: ${BATCH_JDBC_SCHEMA}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            scope:
              - email
            redirect-uri: ${OAUTH2_REDIRECT_URI}