server:
  port: ${SERVER_PORT}

swagger:
  uri: ${SWAGGER_URI}

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: "${REDIS_PASSWORD}"

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: "${DB_PASSWORD}"
    driver-class-name: ${DB_DRIVER}

  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL}

  batch:
    job:
      enabled: ${BATCH_JOB_ENABLED}
    jdbc:
      initialize-schema: ${BATCH_JDBC_SCHEMA}

popularity:
  weight:
    view: ${POPULARITY_WEIGHT_VIEW:1} # 조회 가중치 (double). 미설정 시 기본 1
    bid: ${POPULARITY_WEIGHT_BID:5} # 입찰 가중치 (double). 미설정 시 기본 5
  bucket:
    ttl-minutes: ${POPULARITY_BUCKET_TTL_MINUTES:70} # 분 버킷 TTL. 기본 70분(60분 + 버퍼)
