services:
  tako_ai:
    build:
      context: ../backend-fastapi
      dockerfile: Dockerfile
    container_name: tako_ai
    expose:
      - "8000"
    mem_limit: 1024m
    memswap_limit: 1024m
    cpus: "0.6"
    restart: unless-stopped
    networks:
      - e104_net

networks:
  e104_net:
    external: true