services:
  tako_front_dev:
    build:
      context: ../frontend-web/taako
      dockerfile: Dockerfile
    container_name: tako_front_dev
    mem_limit: 256m
    cpus: "0.25"
    restart: unless-stopped
    networks:
      - e104_net
    env_file:
      - ../deploy/.env

networks:
  e104_net:
    external: true
