services:
  tako_ai:
    build:
      context: ../backend-fastapi
      dockerfile: Dockerfile
    container_name: tako_ai
    ports:
      - "8000:8000"
    mem_limit: 1024m
    memswap_limit: 1024m
    cpus: "0.6"
    restart: unless-stopped
    networks:
      - e104_net
    env_file:
      - .env.ai

networks:
  e104_net:
    external: true