services:
  tako_ai:
    build:
      context: ../backend-fastapi
      dockerfile: Dockerfile
    container_name: tako_ai
    expose:
      - "8000"
    mem_limit: 1024m
    memswap_limit: 1024m
    cpus: "0.6"
    restart: unless-stopped 
    networks:
      - e104_net
    env_file:
      - .env.ai

  tako_ai_dev:
    build:
      context: ../backend-fastapi
      dockerfile: Dockerfile
    container_name: tako_ai_dev
    expose:
      - "8000"
    mem_limit: 1024m
    memswap_limit: 1024m
    cpus: "0.6"
    restart: unless-stopped
    networks:
      - e104_net
    env_file:
      - .env.devai

networks:
  e104_net:
    external: true