INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh12pt5-160', '{"subtypes":["Basic"]}', NULL, 'Rare Secret', 4, 12, '피카츄');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('sm10-33', '{"subtypes":["Basic"]}', NULL, 'Common', 4, 12, '꼬부기');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('sm115-7', '{"subtypes":["Basic"]}', NULL, 'Common', 4, 12, '파이리');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('sm35-1', '{"subtypes":["Basic"]}', NULL, 'Common', 4, 12, '꼬부기');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh12-127', '{"subtypes":["Basic"]}', NULL, 'Common', 4, 12, '토게데마루');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh12-85', '{"subtypes":["Basic"]}', NULL, 'Uncommon', 4, 12, '데덴네');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh12-116', '{"subtypes":["Basic"]}', NULL, 'Uncommon', 4, 12, '모르페코');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('pgo-24', '{"subtypes":["Basic"]}', NULL, 'Rare Holo', 4, 12, '프리저');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('pgo-29', '{"subtypes":["Basic"]}', NULL, 'Rare Holo', 4, 12, '썬더');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('pgo-12', '{"subtypes":["Basic"]}', NULL, 'Rare Holo', 4, 12, '파이어');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh1-85', '{"subtypes":["Stage 2"]}', NULL, 'Rare Holo', 4, 12, '팬텀');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh9-132', '{"subtypes":["Supporter"]}', NULL, 'Rare Holo', 4, 11, '보스의 지령');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('pgo-43', '{"subtypes":["Stage 2"]}', NULL, 'Rare Holo', 4, 12, '마기라스');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swshp-SWSH012', '{"subtypes":["Basic"]}', NULL, 'Rare Holo Cosmos', 4, 12, '모르페코');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh45-60', '{"subtypes":["Supporter"]}', NULL, 'Rare Holo Cosmos', 4, 11, '박사의 연구');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swshp-SWSH127', '{"subtypes":["Basic"]}', NULL, 'Rare Holo Cosmos', 4, 12, '이브이');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('pgo-11', '{"subtypes":["Basic","Radiant"]}', NULL, 'Radiant Rare', 4, 12, '찬란한 리자몽');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh12-59', '{"subtypes":["Basic","Radiant"]}', NULL, 'Radiant Rare', 4, 12, '찬란한 후딘');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh12-120', '{"subtypes":["Basic","Radiant"]}', NULL, 'Radiant Rare', 4, 12, '찬란한 지라치');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh11tg-TG03', '{"subtypes":["Stage 2"]}', NULL, 'trainer gallery rare holo', 4, 12, '리자몽');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh11tg-TG05', '{"subtypes":["Basic"]}', NULL, 'trainer gallery rare holo', 4, 12, '피카츄');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh12tg-TG02', '{"subtypes":["Stage 1"]}', NULL, 'Trainer Gallery Rare Holo', 4, 12, '밀로틱');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh7-110', '{"subtypes":["Basic","V","Rapid Strike"]}', NULL, 'Rare Holo V', 4, 12, '레쿠쟈 V');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh12-138', '{"subtypes":["Basic","V"]}', NULL, 'Rare Holo V', 4, 12, '루기아 V');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('pgo-49', '{"subtypes":["Basic","V"]}', NULL, 'Rare Holo V', 4, 12, '망나뇽 V');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh8-250', '{"subtypes":["Basic","V","Fusion Strike"]}', NULL, 'Rare Ultra', 4, 12, '뮤 V');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh3-183', '{"subtypes":["Basic","V"]}', NULL, 'Rare Ultra', 4, 12, '핫삼 V');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh12-176', '{"subtypes":["Basic","V"]}', NULL, 'Rare Ultra', 4, 12, '안농 V');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swshp-SWSH179', '{"subtypes":["Basic","V","Single Strike"]}', NULL, 'Rare Ultra', 4, 12, '부스터 V');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swshp-SWSH181', '{"subtypes":["Basic","V","Rapid Strike"]}', NULL, 'Rare Ultra', 4, 12, '샤미드 V');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swshp-SWSH183', '{"subtypes":["Basic","V"]}', NULL, 'Rare Ultra', 4, 12, '쥬피썬더 V');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh8-245', '{"subtypes":["Basic","V"]}', NULL, 'Rare Ultra', 4, 12, '세레비 V');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh11-186', '{"subtypes":["Basic","V"]}', NULL, 'Rare Ultra', 4, 12, '기라티나 V');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh10-177', '{"subtypes":["Basic","V"]}', NULL, 'Rare Ultra', 4, 12, '디아루가 오리진 폼 V');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swshp-SWSH180', '{"subtypes":["VMAX","Single Strike"]}', NULL, 'Rare Rainbow', 4, 12, '부스터 VMAX');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swshp-SWSH182', '{"subtypes":["VMAX","Rapid Strike"]}', NULL, 'Rare Rainbow', 4, 12, '샤미드 VMAX');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swshp-SWSH184', '{"subtypes":["VMAX"]}', NULL, 'Rare Rainbow', 4, 12, '쥬피썬더 VMAX');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh7-29', '{"subtypes":["VMAX"]}', NULL, 'Rare Holo VMAX', 4, 12, '갸라도스 VMAX');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh45-51', '{"subtypes":["VMAX"]}', NULL, 'Rare Holo VMAX', 4, 12, '메타몽 VMAX');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh9-29', '{"subtypes":["VMAX"]}', NULL, 'Rare Holo VMAX', 4, 12, '크랩 VMAX');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh8-270', '{"subtypes":["VMAX"]}', NULL, 'Rare Rainbow', 4, 12, '에브이 VMAX');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh8-271', '{"subtypes":["VMAX","Single Strike"]}', NULL, 'Rare Rainbow', 4, 12, '팬텀 VMAX');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh7-215', '{"subtypes":["VMAX","Single Strike"]}', NULL, 'Rare Rainbow', 4, 12, '블래키 VMAX');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('pgo-31', '{"subtypes":["VSTAR"]}', NULL, 'Rare Holo VSTAR', 4, 12, '뮤츠 VMAX');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swshp-SWSH214', '{"subtypes":["VSTAR"]}', NULL, 'Rare Holo VSTAR', 4, 12, '루카리오 VSTAR');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh9-18', '{"subtypes":["VSTAR"]}', NULL, 'Rare Holo VSTAR', 4, 12, '리자몽 VSRAR');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh6-196', '{"subtypes":["Supporter"]}', NULL, 'Rare Ultra', 4, 11, '니아');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh9-167', '{"subtypes":["Supporter"]}', NULL, 'Rare Ultra', 4, 11, '용식');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh1-200', '{"subtypes":["Supporter"]}', NULL, 'Rare Ultra', 4, 11, '마리');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh11tg-TG27', '{"subtypes":["Supporter"]}', NULL, 'Rare Ultra', 4, 11, '야청');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh12tg-TG26', '{"subtypes":["Supporter"]}', NULL, 'Rare Ultra', 4, 11, '버넷박사');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh11tg-TG26', '{"subtypes":["Supporter"]}', NULL, 'Rare Ultra', 4, 11, '순무');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh4-188', '{"subtypes":["VMAX"]}', NULL, 'Rare Rainbow', 4, 12, '피카츄 VMAX');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh12-197', '{"subtypes":["VSTAR"]}', NULL, 'Rare Rainbow', 4, 12, '알로라 식스테일 VSTAR');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh10-204', '{"subtypes":["Supporter"]}', NULL, 'Rare Rainbow', 4, 11, '주혜');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh8-268', '{"subtypes":["VMAX","Fusion Strike"]}', NULL, 'Rare Rainbow', 4, 12, '뮤 VMAX');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh9-175', '{"subtypes":["VSTAR"]}', NULL, 'Rare Rainbow', 4, 12, '엘풍 VSTAR');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh12-205', '{"subtypes":["Supporter"]}', NULL, 'Rare Rainbow', 4, 11, '기모노드레스');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh2-209', '{"subtypes":["Special"]}', NULL, 'Rare Secret', 4, 16, '트윈 에너지');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh9-186', '{"subtypes":["Item"]}', NULL, 'Rare Secret', 4, 9, '마스터볼');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh10-213', '{"subtypes":["Stadium"]}', NULL, 'Rare Secret', 4, 10, '정상으로 가는 눈길');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh8-280', '{"subtypes":["Stage 1"]}', NULL, 'Rare Secret', 4, 12, '보송송');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh9-184', '{"subtypes":["VSTAR"]}', NULL, 'Rare Secret', 4, 12, '아르세우스 VSATR');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh11tg-TG30', '{"subtypes":["VMAX","Fusion Strike"]}', NULL, 'Rare Secret', 4, 12, '뮤 VMAX');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh9tg-TG16', '{"subtypes":["Basic","V"]}', NULL, 'Rare Holo V', 4, 12, '따라큐 V');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh9tg-TG18', '{"subtypes":["Basic","V","Single Strike"]}', NULL, 'Rare Holo V', 4, 12, '일격 우라오스 V');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh11tg-TG16', '{"subtypes":["Basic","V"]}', NULL, 'Rare Holo V', 4, 12, '피카츄 V');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh9tg-TG17', '{"subtypes":["VMAX"]}', NULL, 'Rare Holo VMAX', 4, 12, '따라큐 VMAX');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh9tg-TG19', '{"subtypes":["VMAX","Single Strike"]}', NULL, 'Rare Holo VMAX', 4, 12, '일격 우라오스 VMAX');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh11tg-TG17', '{"subtypes":["VMAX"]}', NULL, 'Rare Holo VMAX', 4, 12, '피카츄 VMAX');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh9-120', '{"subtypes":["Basic"]}', NULL, 'Common', 4, 12, '비버니');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh12-49', '{"subtypes":["Basic"]}', NULL, 'Common', 4, 12, '피카츄');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh8-138', '{"subtypes":["Basic"]}', NULL, 'Common', 4, 12, '롱스톤');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('pgo-69', '{"subtypes":["Stadium"]}', NULL, 'Uncommon', 4, 10, '포켓스톱');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh1-173', '{"subtypes":["Supporter"]}', NULL, 'Uncommon', 4, 11, '포켓몬놀이');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh9-150', '{"subtypes":["Item"]}', NULL, 'Uncommon', 4, 9, '마스터볼');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh4-9', '{"subtypes":["Basic"]}', NULL, 'Amazing Rare', 4, 12, '세레비');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh4-50', '{"subtypes":["Basic"]}', NULL, 'Amazing Rare', 4, 12, '라이코');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh4-82', '{"subtypes":["Basic"]}', NULL, 'Amazing Rare', 4, 12, '자시안');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh4-102', '{"subtypes":["Basic"]}', NULL, 'Amazing Rare', 4, 12, '자마젠타');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh4-119', '{"subtypes":["Basic"]}', NULL, 'Amazing Rare', 4, 12, '지라치');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh4-138', '{"subtypes":["Basic"]}', NULL, 'Amazing Rare', 4, 12, '레쿠쟈');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh45-17', '{"subtypes":["Basic"]}', NULL, 'Amazing Rare', 4, 12, '레시라무');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh45-21', '{"subtypes":["Basic"]}', NULL, 'Amazing Rare', 4, 12, '가이오가');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh45-46', '{"subtypes":["Basic"]}', NULL, 'Amazing Rare', 4, 12, '이벨타르');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh45sv-SV093', '{"subtypes":["Basic"]}', NULL, 'Rare Shiny', 4, 12, '치라미');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh45sv-SV094', '{"subtypes":["Stage 1"]}', NULL, 'Rare Shiny', 4, 12, '치라치노');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh45sv-SV110', '{"subtypes":["Basic","V"]}', NULL, 'Rare Holo V', 4, 12, '라프라스 V');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh45sv-SV023', '{"subtypes":["Basic"]}', NULL, 'Rare Shiny', 4, 12, '가라르 달막화');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh45sv-SV076', '{"subtypes":["Basic"]}', NULL, 'Rare Shiny', 4, 12, '또가스');
INSERT INTO tcg.card (code, description, attribute, rarity, category_major_id, category_medium_id, name) VALUES ('swsh45sv-SV107', '{"subtypes":["VMAX"]}', NULL, 'Rare Holo VMAX', 4, 12, '리자몽 VMAX');